"""user_id fk on Auth setted to unique=True

Revision ID: 3abc8a6bc263
Revises: aae381e6a102
Create Date: 2025-03-19 10:36:29.425724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abc8a6bc263'
down_revision: Union[str, None] = 'aae381e6a102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='unique')
    # ### end Alembic commands ###
