"""Initial Migrations: User:1 and Terreiro:N

Revision ID: 529c02830259
Revises: 
Create Date: 2025-02-13 10:53:25.935132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529c02830259'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('terreiros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('leader', sa.UUID(), nullable=False),
    sa.Column('infrastructure', sa.Text(), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['leader'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader')
    )
    op.create_index(op.f('ix_terreiros_id'), 'terreiros', ['id'], unique=False)
    op.create_index(op.f('ix_terreiros_name'), 'terreiros', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terreiros_name'), table_name='terreiros')
    op.drop_index(op.f('ix_terreiros_id'), table_name='terreiros')
    op.drop_table('terreiros')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
