"""new field added: ENUM users.plan

Revision ID: 651dd6466b39
Revises: c0a68556e7db
Create Date: 2025-03-31 20:14:22.018431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651dd6466b39'
down_revision: Union[str, None] = 'c0a68556e7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_plan_enum = sa.Enum('BASIC','PREMIUM','PROFESSIONAL', name='user_plan')
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    user_plan_enum.create(op.get_bind(),checkfirst=True)
    op.add_column('users', sa.Column('plan', sa.Enum('BASIC', 'PREMIUM', 'PROFESSIONAL', name='user_plan'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    user_plan_enum.drop(op.get_bind(),checkfirst=True)
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
