"""seted medium.user_id to unique=False

Revision ID: 85cf12b86d6b
Revises: d66ac4eb8d19
Create Date: 2025-02-14 10:07:34.524177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cf12b86d6b'
down_revision: Union[str, None] = 'd66ac4eb8d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mediums_user_id_key', 'mediums', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mediums_user_id_key', 'mediums', ['user_id'])
    # ### end Alembic commands ###
