"""cpf and plan seted to nullable=true

Revision ID: 985e9052fad0
Revises: ad81152f7681
Create Date: 2025-02-20 14:34:17.119017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985e9052fad0'
down_revision: Union[str, None] = 'ad81152f7681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('users_cpf_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_cpf_key', 'users', ['cpf'])
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###
