"""new fileds added on User(contact, bio, profile_picture)

Revision ID: 98646dc9563f
Revises: 651dd6466b39
Create Date: 2025-04-07 16:19:50.752223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98646dc9563f'
down_revision: Union[str, None] = '651dd6466b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###
