"""Auth email setted to unique

Revision ID: aae381e6a102
Revises: 3565db1de951
Create Date: 2025-03-19 09:41:33.540266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae381e6a102'
down_revision: Union[str, None] = '3565db1de951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='unique')
    # ### end Alembic commands ###
