"""agent_terreiro created

Revision ID: ad81152f7681
Revises: 74526cd66c3d
Create Date: 2025-02-14 13:56:15.206329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad81152f7681'
down_revision: Union[str, None] = '74526cd66c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agente_terreiros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_terreiro_role', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_terreiro', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_terreiro'], ['terreiros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_terreiro_role'], ['terreiro_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'id_terreiro', name='uq_user_terreiro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agente_terreiros')
    # ### end Alembic commands ###
