"""drop column users.plan

Revision ID: c0a68556e7db
Revises: 7f4f8588b643
Create Date: 2025-03-31 20:08:29.149551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a68556e7db'
down_revision: Union[str, None] = '7f4f8588b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
